@startuml Network Diagram Appointments
header Network Diagram
title Appointments
node "Mobile App" as Mobile_App <<Device>> {

}
node "Application Server" as Application_Server <<Device>> {

}
node "Database Server" as Database_Server <<Device>> {

}
	Mobile_App -down-> Application_Server: Ports: 443\nProtcol:TCP
	Application_Server -down-> Database_Server: Ports: 1443\nProtcol:TCP
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Appointments
header Deployment Diagram
title Appointments
	node "Mobile App" as Mobile_App <<Device>> {
		package "Appointments" as Appointments_Mobile_App_package <<System>>{
			boundary "Appointments App" as Appointments_App <<UI>>
		}
	}

	node "Application Server" as Application_Server <<Device>> {
		package "Appointments" as Appointments_Application_Server_package <<System>>{
			component "Appointments Service" as Appointments_Service <<Service>>
		}
	}

	node "Database Server" as Database_Server <<Device>> {
		package "Appointments" as Appointments_Database_Server_package <<System>>{
			database "Appointments Database" as Appointments_Database <<Database>>
		}
	}

	Appointments_App -down-> Appointments_Service
	Appointments_Service -down-> Appointments_Database
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Appointments
header Component Diagram
title Appointments
package "Appointments" as Appointments_package <<System>>{
	boundary "Appointments App" as Appointments_App <<UI>>
	component "Appointments Service" as Appointments_Service <<Service>>
	database "Appointments Database" as Appointments_Database <<Database>>
}
	Appointments_App -down-> Appointments_Service
	Appointments_Service -down-> Appointments_Database
@enduml

''''''''''''''''''''''''''''''
@startuml System Diagram Appointments
header System Diagram
title Appointments
package "Appointments" as Appointments_package <<System>>
@enduml
