@startuml Network Diagram Identity
header Network Diagram
title Identity
node "Identity Container" as Identity_Container <<Execution Environment>> {

}
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Identity
header Deployment Diagram
title Identity
	Identity_Service -down-( Identity_DB_SQL
	Identity_Service -down-( Event_Bus_Pub_Sub
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Identity
header Component Diagram
title Identity
package "Identity" as Identity_package <<System>>{
	component "Identity Service" as Identity_Service <<Service>>
	database "Identity DB (SQL)" as Identity_DB_SQL <<Database>>
	queue "Event Bus (Pub/Sub)" as Event_Bus_Pub_Sub <<Queue>>
}
	Identity_Service -down-( Identity_DB_SQL
	Identity_Service -down-( Event_Bus_Pub_Sub
@enduml

''''''''''''''''''''''''''''''
@startuml System Diagram Identity
header System Diagram
title Identity
package "Identity" as Identity_package <<System>>
@enduml
