@startuml Network Diagram Microsoft eShop System
header Network Diagram
title Microsoft eShop System
node "MVC Container" as MVC_Container <<Execution Environment>> {

}
@enduml

''''''''''''''''''''''''''''''
@startuml Deployment Diagram Microsoft eShop System
header Deployment Diagram
title Microsoft eShop System
	eShop_Mobile_App -down-( Mobile_Shopping_API
	eShop_Traditional_Webapp -down-( eShop_Webapp_MVC
	eShop_Webapp_MVC -down-( Web_Shopping_API
	eShop_SPA_Webapp -down-( Web_Shopping_API
	Mobile_Shopping_API -down-( Identity_Service
	Mobile_Shopping_API -down-( Catalog_Service
	Mobile_Shopping_API -down-( Ordering_Service
	Mobile_Shopping_API -down-( Basket_Service
	Web_Shopping_API -down-( Identity_Service
	Web_Shopping_API -down-( Catalog_Service
	Web_Shopping_API -down-( Ordering_Service
	Web_Shopping_API -down-( Basket_Service
@enduml

''''''''''''''''''''''''''''''
@startuml Component Diagram Microsoft eShop System
header Component Diagram
title Microsoft eShop System
package "Microsoft eShop System" as Microsoft_eShop_System_package <<System>>{
	boundary "eShop Mobile App" as eShop_Mobile_App <<UI>>
	boundary "eShop SPA Webapp" as eShop_SPA_Webapp <<UI>>
	boundary "eShop Traditional Webapp" as eShop_Traditional_Webapp <<UI>>
	component "eShop Webapp MVC" as eShop_Webapp_MVC <<Service>>
	interface "Mobile Shopping API" as Mobile_Shopping_API
	interface "Web Shopping API" as Web_Shopping_API
	component "Identity Service" as Identity_Service <<Service>>
	component "Catalog Service" as Catalog_Service <<Service>>
	component "Ordering Service" as Ordering_Service <<Service>>
	component "Basket Service" as Basket_Service <<Service>>
}
	eShop_Mobile_App -down-( Mobile_Shopping_API
	eShop_Traditional_Webapp -down-( eShop_Webapp_MVC
	eShop_Webapp_MVC -down-( Web_Shopping_API
	eShop_SPA_Webapp -down-( Web_Shopping_API
	Mobile_Shopping_API -down-( Identity_Service
	Mobile_Shopping_API -down-( Catalog_Service
	Mobile_Shopping_API -down-( Ordering_Service
	Mobile_Shopping_API -down-( Basket_Service
	Web_Shopping_API -down-( Identity_Service
	Web_Shopping_API -down-( Catalog_Service
	Web_Shopping_API -down-( Ordering_Service
	Web_Shopping_API -down-( Basket_Service
@enduml

''''''''''''''''''''''''''''''
@startuml System Diagram Microsoft eShop System
header System Diagram
title Microsoft eShop System
package "Microsoft eShop System" as Microsoft_eShop_System_package <<System>>
@enduml
